# Generated by Django 5.1.1 on 2024-10-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_remove_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='admin_reply_file',
            field=models.FileField(blank=True, null=True, upload_to='admin_replies/'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
