# Generated by Django 5.1.1 on 2024-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('channel_description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='gallery/pdfs/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('channel_image', models.ImageField(blank=True, null=True, upload_to='gallery/images/')),
            ],
        ),
    ]
