# Generated by Django 5.1.1 on 2024-10-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='report_file',
            field=models.FileField(blank=True, help_text='Upload the report in PDF format (admin only).', null=True, upload_to='reports/'),
        ),
    ]
