# Generated by Django 5.1.1 on 2024-10-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0002_userrequest_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
